name: Build APK release

on:
  push:
    tags:
      - "*"

jobs:
  prepare:
    name: Prepare build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
      - name: Set executable permissions to gradlew
        run: chmod +x ./gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Get tag name
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build APK release
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: .
          output-path: cloudcutter-${{ steps.release.outputs.tag }}.apk
          build-type: assemble
      - name: Sign build artifacts
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.release.outputs.tag }}
          files: |
            ${{ steps.sign_app.outputs.signedReleaseFile }}
      - name: Upload workflow artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            ${{ steps.sign_app.outputs.signedReleaseFile }}
